### ISSUE TITLE
Support for bootstrap 4

### ISSUE THREAD

**Issue by Philip-Nunoo** [dgonz64/redux-form-auto#1]

**Comment by dgonz64** [comment]
Good news! I have been working on this. It's not yet announced because it lacks polishing but you can use it already:

    $ npm install redux-form-auto-bootstrap4 --save

I will update references to the project ASAP.

**Comment by dgonz64** [comment]
I updated bootstrap 4 skin, fixing some layout and markup problems! I will be happy to fix any further issues. Thanks for your interest.

**Comment by Philip-Nunoo** [comment]
Great. I encountered an error while trying the bootstrap 4 skin though. I would re-run my project and update you on it.
